# Generated by Django 3.2.11 on 2022-01-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daftarkandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namakandidat', models.TextField(default='', max_length=100)),
                ('nomerurut', models.IntegerField(default='')),
                ('tempatlahir', models.TextField(default='', max_length=100)),
                ('tanggallahir', models.DateField()),
                ('alamat', models.TextField(default='', max_length=100)),
                ('pengalaman', models.TextField(default='', max_length=100)),
                ('prestasi', models.TextField(default='', max_length=100)),
                ('visi', models.TextField(default='', max_length=100)),
                ('misi', models.TextField(default='', max_length=100)),
                ('programkerja', models.TextField(default='', max_length=100)),
                ('kandidat_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='judul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField(default='')),
            ],
        ),
    ]
