# Generated by Django 3.2.8 on 2022-01-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tambahkandidat',
            new_name='daftarkandidat',
        ),
        migrations.DeleteModel(
            name='pemilih',
        ),
        migrations.DeleteModel(
            name='tambahadmin',
        ),
    ]
