# Generated by Django 3.2.11 on 2022-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarkandidat',
            name='namakandidat',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daftarkandidat',
            name='tempatlahir',
            field=models.CharField(default='', max_length=100),
        ),
    ]
