# Generated by Django 3.2.8 on 2022-02-01 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0002_auto_20220201_0221'),
        ('panitia', '0002_auto_20220201_1721'),
    ]

    operations = [
    ]
