# Generated by Django 3.2.8 on 2022-01-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0002_auto_20220113_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarkandidat',
            name='tanggallahir',
            field=models.DateField(),
        ),
    ]
