# Generated by Django 3.2.11 on 2022-02-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0002_auto_20220201_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarkandidat',
            name='nomerurut',
            field=models.IntegerField(default='', unique=True),
        ),
    ]
