# Generated by Django 3.2.11 on 2022-02-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0002_auto_20220201_0221'),
        ('panitia', '0003_alter_daftarkandidat_nomerurut'),
    ]

    operations = [
    ]
