# Generated by Django 3.2.8 on 2022-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0004_auto_20220201_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='Judul',
            field=models.TextField(default=''),
        ),
    ]
