# Generated by Django 3.2.8 on 2022-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0004_auto_20220127_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarkandidat',
            name='alamat',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daftarkandidat',
            name='misi',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daftarkandidat',
            name='namakandidat',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daftarkandidat',
            name='pengalaman',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daftarkandidat',
            name='prestasi',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daftarkandidat',
            name='programkerja',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daftarkandidat',
            name='tempatlahir',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='daftarkandidat',
            name='visi',
            field=models.TextField(default='', max_length=100),
        ),
    ]
