# Generated by Django 3.2.11 on 2022-02-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0004_merge_20220202_1429'),
        ('panitia', '0006_alter_vote_judul'),
    ]

    operations = [
    ]
