# Generated by Django 3.2.8 on 2022-02-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0003_alter_daftarkandidat_nomerurut'),
        ('panitia', '0006_alter_vote_judul'),
    ]

    operations = [
    ]
