# Generated by Django 3.2.11 on 2022-02-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0007_merge_0004_merge_20220202_1429_0006_alter_vote_judul'),
        ('panitia', '0007_merge_20220201_1847'),
    ]

    operations = [
    ]
