# Generated by Django 3.2.11 on 2022-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0008_merge_20220204_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarkandidat',
            name='kandidat_Main_Img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='Judul',
            field=models.CharField(default='', max_length=50),
        ),
    ]
