# Generated by Django 3.2.11 on 2022-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pemilih',
        ),
        migrations.AlterField(
            model_name='user',
            name='panitia',
            field=models.BooleanField(default=True, verbose_name='panitia'),
        ),
    ]
