# Generated by Django 3.2.11 on 2022-02-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220201_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemilih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=26)),
                ('nim', models.IntegerField(default=0, max_length=26)),
                ('prodi', models.CharField(default='', max_length=26)),
            ],
        ),
    ]
