# Generated by Django 3.2.11 on 2022-02-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pemilih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemilih',
            name='nim',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
