# Generated by Django 3.2.11 on 2022-02-01 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_anggota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pemilih',
            old_name='nama',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='anggota',
            name='pemilih',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pemilih'),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pemilih',
            name='nim',
            field=models.IntegerField(),
        ),
    ]
