# Generated by Django 3.2.11 on 2022-01-31 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0001_initial'),
        ('pemilih', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='kandidat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panitia.daftarkandidat'),
        ),
    ]
